Changed code to use Mau3
pelican-plugins/mau-reader pull request #28
Opened 2023-08-14 21:45 UTC by lgiordani

This creates a new version of the package that uses Mau v3.

2023-08-21 09:16 UTC, lgiordani commented
@justinmayer when you have 5 minutes this is ready. I had some issues with tests, but I fixed them now. Thanks!

2023-09-05 09:31 UTC, lgiordani commented
@justinmayer pretty please? :joy_cat: :pray:

2023-09-05 10:04 UTC, justinmayer requested changes
Hey Leonardo. It has been a busier-than-expected summer, so I apologize for the delay in taking a look at this PR.

In addition to the comment I made about not manually fiddling with the version number, there are a number of updated plugin-related "best practices" that I would like to make before the next release of this plugin, assuming that is okay with you. You can see what some of those changes are by looking at the changes I've made to the Cookiecutter Pelican plugin template.

I will make those proposed changes in a separate branch and PR so that you can have a look and tell me what you think.

2023-09-05 10:08 UTC, lgiordani commented on pyproject.toml
> +version = "3.0.0"
@justinmayer thanks, I honestly completely forgot I changed that. I will revert the change. I'll wait for your other PR with the proposed changes, then when that is merged I will rebase this one. Thanks!

2023-09-05 11:59 UTC, justinmayer commented on pyproject.toml
> +version = "3.0.0"
I submitted #29, which I fear brings changes that will require a non-trivial rebase for you. If that is the case, I'm so sorry! 😅

2023-09-05 13:49 UTC, justinmayer commented
The aforementioned PR has been merged, so this PR is ready to be rebased onto current `main` whenever you have a moment. 😊

2023-09-05 14:26 UTC, lgiordani commented
@justinmayer I preferred not to rebase, I manually moved my changes to a new branch and force pushed. The amount of changes was limited and I felt it was faster this way. Ready to be reviewed!

2023-09-05 15:25 UTC, lgiordani commented
@justinmayer I can't remember the process here. Shall I add here the file to release a major version or shall I first merge and then send a PR with that file?

2023-09-05 17:18 UTC, justinmayer commented
While either technique will work equally well, if it were me, I would probably add the `RELEASE.md` file to this branch/PR and then merge it.

2023-09-05 18:36 UTC, justinmayer approved these changes

2023-09-06 11:23 UTC, merged